name: Build iOS IPA (Free Provisioning)

on:
  push:
    branches:
      - main

jobs:
  build_ios:
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
          channel: stable
          cache: true

      - name: Install Dependencies
        run: flutter pub get

      - name: Build IPA with Automatic Signing
        run: flutter build ipa --release --export-options-plist=ios/Runner/ExportOptions_Automatic.plist

      # Debug step: List the contents of the IPA output directory
      - name: List IPA Directory
        run: ls -la build/ios/ipa/

      # Upload the IPA as an artifact
      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-ipa
          path: build/ios/ipa/*.ipa
